### ISSUE TITLE
"Write after end" error

### ISSUE THREAD

**Issue by hemangikhakhi** [tq-bit/node-red-contrib-server-sent-events#2] opened 2023-09-15 10:56 UTC
Every time when I made changes and deploy the node at that time I am getting the below error
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/7561e73b-0228-4899-8890-2086d35b7e0b)

At run time i.e. by clicking on inject node I am getting "done is not a function"
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/525e7f73-c597-4b0d-ba8a-0d24a42a3182)

**Comment by tq-bit** [comment] 2023-09-15 16:11
Hi hemangikhakhi, thank you for your report :) 

can you please provide some more context? 
- What versions of node and node-red are you running?
- What does your full flow look like? Can you please export it and paste it here?

**Comment by hemangikhakhi** [comment] 2023-09-15 16:41
> Hi hemangikhakhi, thank you for your report :)
> 
> can you please provide some more context?
> 
> * What versions of node and node-red are you running?
> * What does your full flow look like? Can you please export it and paste it here?

`[{"id":"d207a3d8.ce07e","type":"http in","z":"e4605825.a089e8","name":"GET /api/subscribe","url":"/api/subscribe","method":"get","upload":false,"swaggerDoc":"","x":420,"y":480,"wires":[["508ee66.92e2618"]]},{"id":"508ee66.92e2618","type":"sse-server","z":"e4605825.a089e8","nodeId":"@tq-bit/node-red-contrib-server-sent-events","nodeVersion":"1.0.6","name":"Send message server event","event":"message","data":"","x":750,"y":560,"wires":[]},{"id":"a20b2f14.d15d1","type":"sse-client","z":"e4605825.a089e8","nodeId":"@tq-bit/node-red-contrib-server-sent-events","nodeVersion":"1.0.6","name":"Subscribe to message server event","url":"https://testnodeml.interplay.iterate.ai/api/subscribe","event":"message","headers":"","x":370,"y":660,"wires":[["b34774bd.a582d8"]]},{"id":"b34774bd.a582d8","type":"json","z":"e4605825.a089e8","name":"Parse JSON","property":"payload","action":"","pretty":false,"x":630,"y":660,"wires":[["68978f30.2a3d7"]]},{"id":"68978f30.2a3d7","type":"console","z":"e4605825.a089e8","name":"","active":true,"tosidebar":true,"console":false,"tostatus":false,"complete":"false","x":860,"y":660,"wires":[]},{"id":"7afe112c.7c206","type":"function","z":"e4605825.a089e8","name":"","func":"var require = context.global.get('require'); \n\n// msg.payload = {\n//   hello: 'world'\n// }\n    let i = 0;\n\n\n let timer = setInterval(write, 1000);\n\n\n    function write() {\n      i++;\n\n      if (i == 4) {\n        // res.write('event: bye\\ndata: bye-bye\\n\\n');\n        msg.payload = { \n            \"event\": \"bye\",\n            \"data\" : \"bye-bye\"\n        }\n        clearInterval(timer);\n       // res.end();\n       node.send(msg);\n        return;\n      }\n\n      msg.payload = {\n          'data:': i\n          \n      }\n      \n      node.send(msg);\n\n}\n\n    write();\n// return msg;","outputs":1,"timeout":10000,"newThread":false,"noerr":0,"x":390,"y":560,"wires":[["508ee66.92e2618"]]},{"id":"42bcdf12.3f8d5","type":"inject","z":"e4605825.a089e8","name":"","topic":"","payload":"","payloadType":"date","repeat":"","crontab":"","once":false,"onceDelay":0.1,"x":120,"y":560,"wires":[["7afe112c.7c206"]]}]`

**Comment by tq-bit** [comment] 2023-09-15 17:44
Unfortunately, I'm not able to reproduce your issue. Here's my setup:

![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/69204418/01f2425e-8380-44f3-b83d-f3fbd15038e7)

I've put in a conditional check for `done` and moved the unsubscribe functions further down the lane. 
Can you please check if your issues still persist?

**Comment by hemangikhakhi** [comment] 2023-09-18 06:25
Where to put a conditional check for `done`?

**Comment by tq-bit** [comment] 2023-09-18 06:28
https://github.com/tq-bit/node-red-contrib-server-sent-events/commit/7a72f360155e48337035f10f860a0772e4bc5659

I also published it to npm and node-red, please update the node and check again

**Comment by hemangikhakhi** [comment] 2023-09-18 06:34
Thanks now it's working.

**Comment by hemangikhakhi** [comment] 2023-09-18 07:05
Still "Write after end" error is present not deploy the flow
![image](https://github.com/tq-bit/node-red-contrib-server-sent-events/assets/65289141/f6810842-a9e1-46fa-a6bf-c8f06cd8ef00)

**Comment by tq-bit** [comment] 2023-12-18 12:42
@hemangikhakhi 
This issue is possibly fixed by this [pull request](https://github.com/tq-bit/node-red-contrib-server-sent-events/pull/5).
Newest version 1.2.1 is on npm. You're welcome to check on this again

**Closed as completed** 2024-01-03 14:28 UTC
